environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
   - ps: Install-Product node $env:nodejs_version
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript

build_script:
   - msbuildsystem build -p @msbuildsystem -w dist/appveyor/ --target bootstrap --env appveyor --no-progress

artifacts:
  - path: dist/3/
