environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -q -g @openmicrostep/msbuildsystem.cli @openmicrostep/tests istanbul coveralls remap-istanbul
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript

build_script:
  - msbuildsystem build -p @msbuildsystem -w dist/1/
  - node dist/1/node/debug/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/2/
  - node dist/2/node/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/3/

test_script:
  - mstests
        -c -t 20000
        dist/3/node/node_modules/@openmicrostep/msbuildsystem.shared.tests/index.js
        dist/3/node/node_modules/@openmicrostep/msbuildsystem.core.tests/index.js
        dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.tests/index.js
        dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.typescript.tests/index.js

artifacts:
  - path: dist/3/
