.build_tpl: &build_tpl
  stage: build
  script:
   - apk add --no-cache git
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -p @msbuildsystem -w dist/gitlab/ --target bootstrap --env gitlab --no-progress

build-6:
  <<: *build_tpl
  image: node:6-alpine

build-8:
  <<: *build_tpl
  image: node:8-alpine

deploy:
  stage: deploy
  image: node:6-alpine
  only:
    - tags
  script:
   - echo "$NPM_AUTH" >> ~/.npmrc
   - apk add --no-cache git
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -p @msbuildsystem -w dist/gitlab/ --target deploy --env gitlab --no-progress
