.build_tpl: &build_tpl
  stage: build
  script:
   - apk add --no-cache git
   - npm install -q -g @openmicrostep/msbuildsystem.cli@^0.5.0 @openmicrostep/tests istanbul coveralls remap-istanbul
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript@^0.5.0
   - msbuildsystem build -p @msbuildsystem -w dist/gitlab/ --target bootstrap --env gitlab --no-progress

build-6:
  <<: *build_tpl
  image: node:6-alpine

deploy:
  stage: deploy
  image: node:6-alpine
  only:
    - tags
  script:
   - apk add --no-cache git
   - npm install -q -g @openmicrostep/msbuildsystem.cli@^0.5.0 @openmicrostep/tests istanbul coveralls remap-istanbul
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript@^0.5.0
   - msbuildsystem build -p @msbuildsystem -w dist/gitlab/ --target deploy --env gitlab --no-progress
