build:
  image: node:6-alpine
  stage: build
  script:
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -p @msbuildsystem -w bootstrap1/
   - node bootstrap1/node/debug/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w bootstrap2/
   - node bootstrap2/node/debug/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  image: node:6-alpine
  stage: test
  dependencies:
   - build
  script:
   - npm install -q -g @openmicrostep/tests
   - mstests -c dist/node/debug/node_modules/@openmicrostep/msbuildsystem.shared.tests/index.js
                dist/node/debug/node_modules/@openmicrostep/msbuildsystem.core.tests/index.js

publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.shared
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.core
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.cli
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.foundation
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.js
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.js.typescript
  dependencies:
   - build
  only:
    - master
  when: manual
  environment: production

auto_publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.shared
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.core
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.cli
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.foundation
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.js
    - npm publish dist/node/debug/node_modules/@openmicrostep/msbuildsystem.js.typescript
  dependencies:
   - build
  only:
    - tags
  environment: production
