build:
  image: node:6-alpine
  stage: build
  script:
   - npm install -q -g @openmicrostep/msbuildsystem.cli
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
   - msbuildsystem build -p @msbuildsystem -w dist/1/
   - node dist/1/node/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/2/
   - node dist/2/node/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/3/
  artifacts:
    expire_in: 31d
    paths:
     - dist/3/

test:
  image: node:6-alpine
  stage: test
  dependencies:
   - build
  script:
   - npm install -q -g @openmicrostep/tests
   - mstests -c dist/3/node/node_modules/@openmicrostep/msbuildsystem.shared.tests/index.js
                dist/3/node/node_modules/@openmicrostep/msbuildsystem.core.tests/index.js
                dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.tests/index.js
                dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.typescript.tests/index.js

publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.shared
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.core
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.cli
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.foundation
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.js
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.typescript
  dependencies:
   - build
  only:
    - master
  when: manual
  environment: production

auto_publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.shared
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.core
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.cli
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.foundation
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.js
    - npm publish dist/3/node/node_modules/@openmicrostep/msbuildsystem.js.typescript
  dependencies:
   - build
  only:
    - tags
  environment: production
