build:
  image: node:6-alpine
  stage: build
  script:
   - npm install -q -g @openmicrostep/msbuildsystem.cli@^0.5.0
   - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript@^0.5.0
   - msbuildsystem build -p @msbuildsystem -w dist/gitlab/ --target bootstrap --env gitlab --no-progress
  artifacts:
    expire_in: 31d
    paths:
     - dist/3/
