before_script:
 - npm set registry $NPM_REGISTRY

build:
  image: node:6
  stage: build
  script:
   - npm install -q -g @msbuildsystem/cli
   - msbuildsystem modules install @msbuildsystem/js.typescript
   - msbuildsystem modules install typescript
   - msbuildsystem build -p @msbuildsystem/ -w bootstrap/
   - node bootstrap/node/debug/node_modules/@msbuildsystem/cli/index.js build -p @msbuildsystem/ -w dist/
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  image: node:6
  stage: test
  dependencies:
   - build
  script:
   - npm install -q -g @microstep/tests
   - mstests dist/node/debug/node_modules/@msbuildsystem/{shared,core}.tests/index.js
