before_script:
 - npm set registry $NPM_REGISTRY

build:
  image: node:6-alpine
  stage: build
  script:
   - npm install -q -g @msbuildsystem/cli
   - msbuildsystem modules install @msbuildsystem/js.typescript
   - msbuildsystem modules install typescript
   - msbuildsystem build -p @msbuildsystem/ -w bootstrap/
   - node bootstrap/node/debug/node_modules/@msbuildsystem/cli/index.js build -p @msbuildsystem/ -w dist/
  artifacts:
    expire_in: 31d
    paths:
     - dist/

test:
  image: node:6-alpine
  stage: test
  dependencies:
   - build
  script:
   - npm install -q -g @microstep/tests
   - mstests dist/node/debug/node_modules/@msbuildsystem/{shared,core}.tests/index.js

publish:
  image: node:6-alpine
  stage: deploy
  script:
    - echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/shared
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/core
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/cli
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/foundation
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/js
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/js.typescript
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/aspects
    - npm publish bootstrap/node/debug/node_modules/@msbuildsystem/js.logitud
  dependencies:
   - build
  only:
    - master
  when: manual
  environment: production
