language: node_js
node_js:
  - "6"
  - "7"

script:
  - stty cols 80
  - npm install -q -g @openmicrostep/msbuildsystem.cli
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
  - msbuildsystem build -p @msbuildsystem -w bootstrap1/
  - node bootstrap1/node/debug/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w bootstrap2/
  - node bootstrap2/node/debug/node_modules/@openmicrostep/msbuildsystem.cli/index.js build -p @msbuildsystem -w dist/
  - npm install -q -g @openmicrostep/tests
  - mstests -c dist/node/debug/node_modules/@openmicrostep/msbuildsystem.shared.tests/index.js dist/node/debug/node_modules/@openmicrostep/msbuildsystem.core.tests/index.js
