language: node_js
node_js:
  - "6"
  - "7"

script:
  - npm install -q -g @openmicrostep/msbuildsystem.cli@^0.5.0 @openmicrostep/tests istanbul coveralls remap-istanbul
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript@^0.5.0
  - msbuildsystem build -p @msbuildsystem -w dist/travis/ --target bootstrap --env travis --no-progress
