language: node_js
node_js:
  - "6"
  - "8"

script:
  - npm install -q -g @openmicrostep/msbuildsystem.cli
  - msbuildsystem modules install @openmicrostep/msbuildsystem.js.typescript
  - msbuildsystem build -p @msbuildsystem -w dist/travis/ --target bootstrap --env travis --no-progress
